version: 0.2

phases:
  install:
    commands:
      - cd poc_app/front_end && npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo PRE_BUILD Phase
      - npm install
  build:
    commands:
      - echo BUILD Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync .nuxt $S3_BUCKET
