version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo PRE_BUILD Phase
      - cd poc_app/front_end && npm install
  build:
    commands:
      - echo BUILD Phase
      - cd poc_app/front_end && npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./poc_app/front_end/dist $S3_BUCKET
